# Generated by Django 4.2.5 on 2023-10-01 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('Age', models.IntegerField(max_length=3)),
                ('email', models.EmailField(max_length=70)),
                ('pincode', models.IntegerField(max_length=8)),
                ('Address', models.IntegerField(max_length=70)),
                ('phone', models.PositiveIntegerField()),
            ],
        ),
    ]
